# Generated by Django 5.0.2 on 2024-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'About Table',
            },
        ),
    ]
