# Generated by Django 5.0.2 on 2024-03-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='service_images')),
            ],
            options={
                'verbose_name_plural': 'our service',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About us'},
        ),
    ]
