# Generated by Django 5.0.2 on 2024-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_service_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200)),
                ('text2', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_images')),
            ],
            options={
                'verbose_name_plural': 'Our Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Our Service'},
        ),
    ]
