# Generated by Django 5.0.2 on 2024-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_project_alter_about_options_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testimonial_images')),
            ],
            options={
                'verbose_name_plural': 'Our Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Our Services'},
        ),
    ]
