# Generated by Django 5.0.2 on 2024-03-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_testimonial_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
