# Generated by Django 5.0.2 on 2024-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='default_author_image.jpg', upload_to='author_images/'),
        ),
    ]
